go mod why -m github.com/BurntSushi/toml > why.txt
go mod why -m github.com/StackExchange/wmi >> why.txt
go mod why -m github.com/aead/ecdh >> why.txt
go mod why -m github.com/allegro/bigcache >> why.txt
go mod why -m github.com/davecgh/go-spew >> why.txt
go mod why -m github.com/deckarep/golang-set >> why.txt
go mod why -m github.com/go-ole/go-ole >> why.txt
go mod why -m github.com/go-stack/stack >> why.txt
go mod why -m github.com/golang-collections/collections >> why.txt
go mod why -m github.com/golang/mock >> why.txt
go mod why -m github.com/golang/protobuf >> why.txt
go mod why -m github.com/golang/snappy >> why.txt
go mod why -m github.com/hashicorp/golang-lru >> why.txt
go mod why -m github.com/kr/pretty >> why.txt
go mod why -m github.com/mattn/go-colorable >> why.txt
go mod why -m github.com/mattn/go-isatty >> why.txt
go mod why -m github.com/patrickmn/go-cache >> why.txt
go mod why -m github.com/pkg/errors >> why.txt
go mod why -m github.com/rs/cors >> why.txt
go mod why -m github.com/shirou/gopsutil >> why.txt
go mod why -m github.com/stretchr/testify >> why.txt
go mod why -m github.com/syndtr/goleveldb >> why.txt
go mod why -m github.com/tklauser/go-sysconf >> why.txt
go mod why -m github.com/tyler-smith/go-bip39 >> why.txt
go mod why -m go.uber.org/atomic >> why.txt
go mod why -m golang.org/x/crypto >> why.txt
go mod why -m golang.org/x/net >> why.txt
go mod why -m golang.org/x/sys >> why.txt
go mod why -m google.golang.org/protobuf >> why.txt
go mod why -m gopkg.in/check.v1 >> why.txt
go mod why -m gopkg.in/natefinch/lumberjack.v2 >> why.txt
go mod why -m gopkg.in/natefinch/npipe.v2 >> why.txt
go mod why -m gopkg.in/urfave/cli.v1 >> why.txt
