unit common.db.xleveldb.filter.bloom;

interface

uses
  System.SysUtils,
  System.Classes,
  System.Generics.Collections,
  common.db.xleveldb.filter.filter,
  common.db.xleveldb.util; // For Hash function

type
  TBloomFilter = class(TInterfacedObject, IFilter)
  private
    FBitsPerKey: Integer;
  public
    constructor Create(BitsPerKey: Integer);
    function Name: string; override;
    function Contains(const Filter, Key: TBytes): Boolean; override;
    function NewGenerator: IFilterGenerator; override;
  end;

type
  TBloomFilterGenerator = class(TInterfacedObject, IFilterGenerator)
  private
    FN: Integer;
    FK: Byte;
    FKeyHashes: TArray<Cardinal>;
  public
    constructor Create(AN: Integer; AK: Byte);
    procedure Add(const Key: TBytes); override;
    procedure Generate(B: IBuffer); override;
  end;

function NewBloomFilter(BitsPerKey: Integer): IFilter;

implementation

function BloomHash(const Key: TBytes): Cardinal;
begin
  Result := Hash(Key, $bc9f1d34); // Assuming Hash function is available from common.db.xleveldb.util
end;

{ TBloomFilter }

constructor TBloomFilter.Create(BitsPerKey: Integer);
begin
  FBitsPerKey := BitsPerKey;
end;

function TBloomFilter.Name: string;
begin
  Result := 'leveldb.BuiltinBloomFilter';
end;

function TBloomFilter.Contains(const Filter, Key: TBytes): Boolean;
var
  NBytes: Integer;
  NBits: Cardinal;
  K: Byte;
  KH: Cardinal;
  Delta: Cardinal;
  J: Byte;
  BitPos: Cardinal;
begin
  NBytes := Length(Filter) - 1;
  if NBytes < 1 then
    Exit(False);
  NBits := Cardinal(NBytes * 8);

  // Use the encoded k so that we can read filters generated by
  // bloom filters created using different parameters.
  K := Filter[NBytes];
  if K > 30 then
    Exit(True); // Reserved for potentially new encodings for short bloom filters. Consider it a match.

  KH := BloomHash(Key);
  Delta := (KH shr 17) or (KH shl 15); // Rotate right 17 bits
  for J := 0 to K - 1 do
  begin
    BitPos := KH mod NBits;
    if (Cardinal(Filter[BitPos div 8]) and (1 shl (BitPos mod 8))) = 0 then
      Exit(False);
    KH := KH + Delta;
  end;
  Result := True;
end;

function TBloomFilter.NewGenerator: IFilterGenerator;
var
  K: Byte;
begin
  // Round down to reduce probing cost a little bit.
  K := Byte(FBitsPerKey * 69 div 100); // 0.69 =~ ln(2)
  if K < 1 then
    K := 1
  else if K > 30 then
    K := 30;
  Result := TBloomFilterGenerator.Create(FBitsPerKey, K);
end;

{ TBloomFilterGenerator }

constructor TBloomFilterGenerator.Create(AN: Integer; AK: Byte);
begin
  FN := AN;
  FK := AK;
  SetLength(FKeyHashes, 0);
end;

procedure TBloomFilterGenerator.Add(const Key: TBytes);
begin
  // Use double-hashing to generate a sequence of hash values.
  // See analysis in [Kirsch,Mitzenmacher 2006].
  FKeyHashes := FKeyHashes + [BloomHash(Key)];
end;

procedure TBloomFilterGenerator.Generate(B: IBuffer);
var
  NBits: Cardinal;
  NBytes: Cardinal;
  Dest: TBytes;
  KH: Cardinal;
  Delta: Cardinal;
  J: Byte;
  BitPos: Cardinal;
begin
  // Compute bloom filter size (in both bits and bytes)
  NBits := Cardinal(Length(FKeyHashes) * FN);
  // For small n, we can see a very high false positive rate. Fix it
  // by enforcing a minimum bloom filter length.
  if NBits < 64 then
    NBits := 64;
  NBytes := (NBits + 7) div 8;
  NBits := NBytes * 8;

  Dest := B.Alloc(Integer(NBytes) + 1);
  Dest[NBytes] := FK;
  for KH in FKeyHashes do
  begin
    Delta := (KH shr 17) or (KH shl 15); // Rotate right 17 bits
    for J := 0 to FK - 1 do
    begin
      BitPos := KH mod NBits;
      Dest[BitPos div 8] := Dest[BitPos div 8] or (1 shl (BitPos mod 8));
      KH := KH + Delta;
    end;
  end;

  SetLength(FKeyHashes, 0);
end;

function NewBloomFilter(BitsPerKey: Integer): IFilter;
begin
  Result := TBloomFilter.Create(BitsPerKey);
end;

end.
