unit Ledger.Consensus.Core.Mock.SBP.Reader;

interface

// This unit is a placeholder for a mock implementation of ISBPStatReader.
// In Delphi, mocking is typically done using a framework like Delphi Mocks or DUnitX's own mocking capabilities.
// The Go code was generated by MockGen and relies on the gomock framework.
// A direct translation of the generated mock is not practical.
// Instead, we define the interface and a note that a mock should be created in the test code where needed.

uses
  System.SysUtils,
  System.Generics.Collections,
  Common.Types,
  Ledger.Consensus.Core.TimeIndex,
  Ledger.Consensus.Core.SBP.Reader; // Assuming SBP.Reader defines the stats records and ISBPStatReader

type
  // In a test unit, you would use a mocking framework to create a mock of ISBPStatReader.
  // For example, with Delphi Mocks:
  // var
  //   MockReader: TMock<ISBPStatReader>;
  // begin
  //   MockReader := TMock<ISBPStatReader>.Create;
  //   MockReader.Setup.WillReturn(SomeDayStatsArray).When.DayStats(any, any);
  //   ...
  // end;
  IMockSBPStatReader = interface(ISBPStatReader)
    ['{DA4C3F5E-6B3A-4F8C-9E1D-3C9A6E5F7B1D}']
  end;

implementation

end.
